---
- name: Beets
  docker_container:
    name: beets
    image: linuxserver/beets
    pull: true
    volumes:
      - "{{ beets_config_directory }}:/config:rw"
      - "{{ emby_movies_directory }}:/movies:{{ emby_movies_permissions }}"
    ports:
      - "{{ beets_port_http }}:8337"
    network_mode: host
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ beets_user_id }}"
      PGID: "{{ beets_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "emby"
      traefik.frontend.rule: "Host:emby.{{ ansible_nas_domain }}"
      traefik.enable: "{{ emby_available_externally }}"
      traefik.port: "8096"