---
- name: Create beets config directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ beets_config_directory }}"

- name: Template beets configuration
  template:
    src: beets/config.yaml
    dest: "{{ beets_config_directory }}/config.yaml"

- name: Beets
  docker_container:
    name: beets
    image: linuxserver/beets
    pull: true
    volumes:
      - "{{ beets_config_directory }}:/config:rw"
      - "{{ music_root }}:/music:rw"
      - "{{ beets_ingest_directory }}:/downloads:rw"
    ports:
      - "{{ beets_port_http }}:8337"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ beets_user_id }}"
      PGID: "{{ beets_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "beets"
      traefik.frontend.rule: "Host:beets.{{ ansible_nas_domain }}"
      traefik.enable: "{{ beets_available_externally }}"
      traefik.port: "8096"

- name: Declare Beets as service
  copy:
    src: files/beets/beets.service
    dest: /etc/systemd/system/beets.service
    mode: '0644'

- name: Setup a 15 minute recurring timer for Beets
  copy:
    src: files/beets/beets.timer
    dest: /etc/systemd/system/beets.timer
    mode: '0644'

- name: Enable timer for Beets import
  systemd:
    name: beets.timer
    enabled: yes
    state: started

- name: Reload Systemd
  systemd:
    daemon_reload: yes