---
- name: Create beets config directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ beets_config_directory }}"

- name: Template beets configuration
  template:
    src: beets/config.yaml
    dest: "{{ beets_config_directory }}/config.yaml"

- name: Beets
  docker_container:
    name: beets
    image: linuxserver/beets
    pull: true
    volumes:
      - "{{ beets_config_directory }}:/config:rw"
      - "{{ music_root }}:/music:rw"
      - "{{ downloads_root }}:/downloads:ro"
    ports:
      - "{{ beets_port_http }}:8337"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ beets_user_id }}"
      PGID: "{{ beets_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "beets"
      traefik.frontend.rule: "Host:beets.{{ ansible_nas_domain }}"
      traefik.enable: "{{ beets_available_externally }}"
      traefik.port: "8096"